# Generated by Django 4.1.5 on 2023-02-28 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3, message='too small task')], verbose_name='Title of task')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
