# Generated by Django 4.1.5 on 2023-02-28 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='delete',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created time'),
            preserve_default=False,
        ),
    ]
